#default container tegistry tag with: your-organisation/example-image
#Google cloud tag with: gcr.io/your-project-id/example-image

IMAGE = standalone
VERSION ?= v2
#PORTS = -p 8080:80
PORTS =
# VOLUMES = -v /var/log/docker:/var/log
VOLUMES =
# ENV = -e SOME_KEY=SOME_VALUE
ENV =

include ../container.make
